# LeNet in Keras

In [1]:
from tensorflow import keras

2025-11-17 18:56:57.791002: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-11-17 18:56:57.812668: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-11-17 18:56:57.942768: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-11-17 18:56:57.943366: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-11-17 18:56:58.881037: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not fin

In [16]:
input_shape = (28, 28, 1)

In [19]:
model = keras.Sequential([
    keras.Input(shape=input_shape),
    keras.layers.Conv2D(filters=6, kernel_size=(5, 5), activation='sigmoid', input_shape=input_shape, padding='same'),
    keras.layers.AveragePooling2D(pool_size=(2, 2), strides=2),
    keras.layers.Conv2D(filters=16, kernel_size=(5, 5), activation='sigmoid', padding='valid'),
    keras.layers.AveragePooling2D(pool_size=(2, 2), strides=2),
    keras.layers.Flatten(),
    keras.layers.Dense(120, activation='sigmoid'),
    keras.layers.Dense(84, activation='sigmoid'),
    keras.layers.Dense(10, activation='softmax')
])

In [20]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
                metrics=['accuracy'])
model.summary()


Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_6 (Conv2D)           (None, 28, 28, 6)         156       
                                                                 
 average_pooling2d_6 (Averag  (None, 14, 14, 6)        0         
 ePooling2D)                                                     
                                                                 
 conv2d_7 (Conv2D)           (None, 10, 10, 16)        2416      
                                                                 
 average_pooling2d_7 (Averag  (None, 5, 5, 16)         0         
 ePooling2D)                                                     
                                                                 
 flatten_3 (Flatten)         (None, 400)               0         
                                                                 
 dense_9 (Dense)             (None, 120)              

In [21]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [8]:
# normalize the images to the range [0, 1]
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

In [10]:
# add a channel dimension to the images
x_train = x_train.reshape(x_train.shape[0], 28, 28, 1)
x_test = x_test.reshape(x_test.shape[0], 28, 28, 1)



In [11]:
# print out the shapes of the datasets
print("x_train shape:", x_train.shape)
print("y_train shape:", y_train.shape)
print("x_test shape:", x_test.shape)
print("y_test shape:", y_test.shape)

x_train shape: (60000, 28, 28, 1)
y_train shape: (60000,)
x_test shape: (10000, 28, 28, 1)
y_test shape: (10000,)


In [13]:
# convert labels to one-hot encoding
y_train = keras.utils.to_categorical(y_train, num_classes=10) 
y_test = keras.utils.to_categorical(y_test, num_classes=10)

In [14]:
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [22]:
# start training the model
model.fit(x_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
1500/1500 [==============================] - 11s 7ms/step - loss: 0.6331 - accuracy: 0.8115 - val_loss: 0.1929 - val_accuracy: 0.9438
Epoch 2/10
1500/1500 [==============================] - 9s 6ms/step - loss: 0.1564 - accuracy: 0.9531 - val_loss: 0.1145 - val_accuracy: 0.9650
Epoch 3/10
1500/1500 [==============================] - 10s 7ms/step - loss: 0.1051 - accuracy: 0.9682 - val_loss: 0.0839 - val_accuracy: 0.9745
Epoch 4/10
1500/1500 [==============================] - 10s 6ms/step - loss: 0.0831 - accuracy: 0.9746 - val_loss: 0.0687 - val_accuracy: 0.9808
Epoch 5/10
1500/1500 [==============================] - 10s 6ms/step - loss: 0.0706 - accuracy: 0.9785 - val_loss: 0.0720 - val_accuracy: 0.9794
Epoch 6/10
1500/1500 [==============================] - 10s 7ms/step - loss: 0.0604 - accuracy: 0.9812 - val_loss: 0.0623 - val_accuracy: 0.9825
Epoch 7/10
1500/1500 [==============================] - 10s 6ms/step - loss: 0.0542 - accuracy: 0.9832 - val_loss: 0.0593 - val_acc

In [32]:
# predict the labels for test dataset
model.evaluate(x_test, y_test, batch_size=32)

313/313 [==============================] - 1s 3ms/step - loss: 0.0386 - accuracy: 0.9874


[0.038632724434137344, 0.9873999953269958]

In [33]:
predictions = model.predict(x_test)

313/313 [==============================] - 1s 2ms/step


In [39]:
import numpy as np

prediction_labels = np.argmax(predictions, axis=1)

In [40]:
prediction_labels

array([7, 2, 1, ..., 4, 5, 6])

In [41]:
prediction_labels.shape

(10000,)

In [42]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [44]:
wrong_count = 0

for i, label in enumerate(prediction_labels):
    if label != y_test[i]:
        wrong_count += 1
        #print(f"Misclassified sample index: {i}, Predicted label: {label}, True label: {y_test[i]}")   
        # 
print(f"Total misclassified samples: {wrong_count} out of {len(y_test)}") 

Total misclassified samples: 126 out of 10000
